### ISSUE TITLE
Should not be required to be part of the config

### ISSUE THREAD

**Issue by BaardBouvet** [sesam-community/github-autodeployer#2]
I think this should not require itself to be part of the config, but just add itself during the sync. That way this can be added to a node much more smoothly and we avoid the whole "suicide" problem.

**Comment by ashkanvahidishams** [comment]
I agree with you if this was only meant to auto deploy. But this will take away the functionality of the micro service to prohibit config being added directly to the node. 

Per now the micro service will automatically remove config that is not meant to be there by continuously  diffing against the github repository.

**Comment by BaardBouvet** [comment]
Yes, it should remove everything except the config it's uploading and itself (by adding it self to the config before the upload happens).

**Comment by BaardBouvet** [comment]
This pattern is the same as the TDD tool adding the scheduler system when testing.

**Comment by ashkanvahidishams** [comment]
Yes, but this does not prohibit people from changing the config directly in the node. Lets say that there is no development in the node for a long time - If the MS only is used whenever there is a PR to the node, the continuous check will not work(?)

**Comment by BaardBouvet** [comment]
But isn't that the same problem as we have now? This microservice should do exactly what it does today, except _not_ mess with the system with _id watcher in the node.

**Comment by ashkanvahidishams** [comment]
I agree with you. This behavior should be fixed.

**Comment by 4hlberg** [comment]
This has been fixed with the newest pull request, closing
